apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zeebe-node-watcher-role
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes"]
    verbs: ["get", "list", "watch", "patch"]