apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: zeebe-node-watcher
  namespace: {{ .Values.namespace | quote }}
  labels:
    app: zeebe-node-watcher
spec:
  selector:
    matchLabels:
      app: zeebe-node-watcher
  template:
    metadata:
      labels:
        app: zeebe-node-watcher
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name | quote }}
      nodeSelector:
        node-role.kubernetes.io/zeebe: ""  # Restrict to nodes with this label
      containers:
      - name: watcher
        image: {{ .Values.image.repository | quote }}:{{ .Values.image.tag | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command:
          - /bin/sh
          - -c
          - |
            NODE_NAME=$(echo $MY_NODE_NAME)
            echo "Watching for terminating Zeebe broker pods on node $NODE_NAME..."
            kubectl get pods -l app.kubernetes.io/component=zeebe-broker --watch -o json | jq -c '. | select(.object.metadata.deletionTimestamp != null)' | while read -r event; do
              POD_NODE=$(echo $event | jq -r '.object.spec.nodeName')
              POD_NAME=$(echo $event | jq -r '.object.metadata.name')
              
              # Check if pod is controlled by a StatefulSet
              OWNER_KIND=$(echo $event | jq -r '.object.metadata.ownerReferences[] | select(.controller == true) | .kind')
              if [ "$POD_NODE" = "$NODE_NAME" ] && [ "$OWNER_KIND" = "StatefulSet" ]; then
                echo "StatefulSet-controlled Pod $POD_NAME (Zeebe broker) is terminating on $NODE_NAME. Tainting node to prevent rescheduling on this node..."
                kubectl taint nodes $NODE_NAME zeebe-broker-terminating=true:NoSchedule --overwrite
                while kubectl get pod $POD_NAME >/dev/null 2>&1; do
                  sleep 1
                done
                echo "Pod $POD_NAME fully terminated. Keeping taint for 30 seconds to allow rescheduling elsewhere..."
                sleep 30
                kubectl taint nodes $NODE_NAME zeebe-broker-terminating:NoSchedule-
                echo "Taint removed from $NODE_NAME. Pod can now schedule on other nodes."
              fi
            done
        env:
        - name: MY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu | quote }}
            memory: {{ .Values.resources.limits.memory | quote }}
          requests:
            cpu: {{ .Values.resources.requests.cpu | quote }}
            memory: {{ .Values.resources.requests.memory | quote }}
